<a href="https://colab.research.google.com/github/Emrul-Hasan-Emon/Generative-AI/blob/main/2.%20Feature%20Extraction/text_representation_and_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
data = np.array([['Red'], ['Green'], ['Blue'], ['Red'], ['Blue']])

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output = False)  # sparse_output=False returns an array

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

In [2]:
encoded_data

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

# Bag of Words (BoW)

In [5]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df = pd.DataFrame({"text":["people watch Emrul Hasan Emon",
                         "Emrul Hasan Emon watch many tutorials",
                         "people write comment",
                          "Emrul Hasan Emon write comment"],"output":[1,1,0,0]})

df

                                    text  output
0          people watch Emrul Hasan Emon       1
1  Emrul Hasan Emon watch many tutorials       1
2                   people write comment       0
3         Emrul Hasan Emon write comment       0

In [6]:
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df['text'])

In [8]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 19 stored elements and shape (4, 9)>

In [9]:
bow.toarray()

array([[0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1]])

In [12]:
# Vocabulary
print(cv.vocabulary_)

{'people': 5, 'watch': 7, 'emrul': 2, 'hasan': 3, 'emon': 1, 'many': 4, 'tutorials': 6, 'write': 8, 'comment': 0}

# N-Grams

In [13]:
df = pd.DataFrame({"text":["people watch Emrul Hasan Emon",
                         "Emrul Hasan Emon watch many tutorials",
                         "people write comment",
                          "Emrul Hasan Emon write comment"],"output":[1,1,0,0]})

df

                                    text  output
0          people watch Emrul Hasan Emon       1
1  Emrul Hasan Emon watch many tutorials       1
2                   people write comment       0
3         Emrul Hasan Emon write comment       0

## BI Grams

In [18]:
ngram_vectorizer = CountVectorizer(ngram_range = (2, 2))

In [19]:
ngram = ngram_vectorizer.fit_transform(df['text'])

In [20]:
ngram.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 1]])

In [21]:
print(ngram_vectorizer.vocabulary_)

{'people watch': 5, 'watch emrul': 7, 'emrul hasan': 2, 'hasan emon': 3, 'emon watch': 0, 'watch many': 8, 'many tutorials': 4, 'people write': 6, 'write comment': 9, 'emon write': 1}

## TRI Grams

In [22]:
ngram_vectorizer = CountVectorizer(ngram_range = (3, 3))

In [23]:
ngram = ngram_vectorizer.fit_transform(df['text'])

In [24]:
ngram.toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0]])

In [25]:
print(ngram_vectorizer.vocabulary_)

{'people watch emrul': 5, 'watch emrul hasan': 7, 'emrul hasan emon': 2, 'hasan emon watch': 3, 'emon watch many': 0, 'watch many tutorials': 8, 'people write comment': 6, 'hasan emon write': 4, 'emon write comment': 1}

# TF-IDF (Term frequency- Inverse Document Frequency)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
df = pd.DataFrame({"text":["people watch Emrul Hasan Emon",
                         "Emrul Hasan Emon watch many tutorials",
                         "people write comment",
                          "Emrul Hasan Emon write comment"],"output":[1,1,0,0]})

df

                                    text  output
0          people watch Emrul Hasan Emon       1
1  Emrul Hasan Emon watch many tutorials       1
2                   people write comment       0
3         Emrul Hasan Emon write comment       0

In [28]:
tfidf = TfidfVectorizer()

In [30]:
arr = tfidf.fit_transform(df['text']).toarray()

In [31]:
arr

array([[0.        , 0.40650968, 0.40650968, 0.40650968, 0.        ,
        0.50212033, 0.        , 0.50212033, 0.        ],
       [0.        , 0.32556244, 0.32556244, 0.32556244, 0.51005648,
        0.        , 0.51005648, 0.40213439, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.        , 0.57735027],
       [0.50212033, 0.40650968, 0.40650968, 0.40650968, 0.        ,
        0.        , 0.        , 0.        , 0.50212033]])